"""Signed model-artifact identity and admission contracts."""

from kairyu.artifacts.manifest import (
    InvalidModelArtifactError,
    ModelArtifactAdmission,
    ModelArtifactAdmissionError,
    ModelArtifactAdmissionRequest,
    ModelArtifactBlob,
    ModelArtifactManifest,
    ModelArtifactQuantization,
    ModelArtifactResourceEstimate,
    ModelArtifactTokenizer,
    ModelArtifactTrustStore,
    SignedModelArtifactManifest,
    TrustedModelSigner,
    VerifiedModelArtifact,
    admit_model_artifact,
    canonical_model_manifest_bytes,
    load_model_artifact_admission_request,
    load_model_artifact_trust_store,
    load_signed_model_artifact,
    model_file_tree_digest,
    model_manifest_digest,
    sign_model_artifact_manifest,
    verify_model_artifact_manifest,
)

__all__ = [
    "InvalidModelArtifactError",
    "ModelArtifactAdmission",
    "ModelArtifactAdmissionError",
    "ModelArtifactAdmissionRequest",
    "ModelArtifactBlob",
    "ModelArtifactManifest",
    "ModelArtifactQuantization",
    "ModelArtifactResourceEstimate",
    "ModelArtifactTokenizer",
    "ModelArtifactTrustStore",
    "SignedModelArtifactManifest",
    "TrustedModelSigner",
    "VerifiedModelArtifact",
    "admit_model_artifact",
    "canonical_model_manifest_bytes",
    "load_model_artifact_admission_request",
    "load_model_artifact_trust_store",
    "load_signed_model_artifact",
    "model_file_tree_digest",
    "model_manifest_digest",
    "sign_model_artifact_manifest",
    "verify_model_artifact_manifest",
]
