"""Logical Runner lifecycle contracts used by serving controllers."""

from kairyu.runners.kubernetes import (
    GPU_UUIDS_ANNOTATION,
    MODEL_ID_ANNOTATION,
    MODEL_REVISION_ANNOTATION,
    RELEASE_ID_ANNOTATION,
    RUNNER_CONTAINER_ANNOTATION,
    KubernetesRunnerPodSnapshot,
    KubernetesRunnerWatcher,
    RunnerRuntimeSource,
    parse_ready_endpoint_uids,
    parse_runner_pods,
)
from kairyu.runners.lifecycle import (
    InvalidRunnerStartupReportError,
    InvalidRunnerTransitionError,
    complete_startup_phase,
    skip_startup_phase,
    start_startup_phase,
    transition_runner_status,
    validate_runner_transition,
    validate_startup_report_update,
)
from kairyu.runners.models import (
    OPTIONAL_RUNNER_STARTUP_PHASES,
    RUNNER_STARTUP_PHASES,
    RunnerFailure,
    RunnerStartupPhase,
    RunnerStartupPhaseOutcome,
    RunnerStartupPhaseReport,
    RunnerStartupReport,
    RunnerState,
    RunnerStatus,
)
from kairyu.runners.observation import (
    KubernetesPodPhase,
    RunnerObservation,
    RunnerObservationBatch,
    RunnerPodObservation,
    RunnerRuntimeObservation,
)
from kairyu.runners.reconciler import (
    InvalidRunnerObservationError,
    RunnerStatusReconciler,
    reconcile_runner_status,
    runner_is_routing_eligible,
)

__all__ = [
    "RUNNER_STARTUP_PHASES",
    "OPTIONAL_RUNNER_STARTUP_PHASES",
    "InvalidRunnerStartupReportError",
    "InvalidRunnerTransitionError",
    "InvalidRunnerObservationError",
    "KubernetesPodPhase",
    "KubernetesRunnerPodSnapshot",
    "KubernetesRunnerWatcher",
    "RunnerRuntimeSource",
    "RELEASE_ID_ANNOTATION",
    "RUNNER_CONTAINER_ANNOTATION",
    "MODEL_ID_ANNOTATION",
    "MODEL_REVISION_ANNOTATION",
    "GPU_UUIDS_ANNOTATION",
    "RunnerFailure",
    "RunnerObservation",
    "RunnerObservationBatch",
    "RunnerPodObservation",
    "RunnerRuntimeObservation",
    "RunnerStartupPhase",
    "RunnerStartupPhaseOutcome",
    "RunnerStartupPhaseReport",
    "RunnerStartupReport",
    "RunnerState",
    "RunnerStatus",
    "RunnerStatusReconciler",
    "complete_startup_phase",
    "parse_ready_endpoint_uids",
    "parse_runner_pods",
    "reconcile_runner_status",
    "runner_is_routing_eligible",
    "skip_startup_phase",
    "start_startup_phase",
    "transition_runner_status",
    "validate_runner_transition",
    "validate_startup_report_update",
]
